### ISSUE TITLE
克隆代码看了一下，应该是依赖版本冲突的问题导致的。

### ISSUE THREAD

**Issue by SalHe** [ExerciseBook/okhttp-issue-in-kotlin#1]
## 简述

在IDEA的`Gradle`面板中可以查看`framework`和`project`的Okhttp版本，发现他们是不一致的。

![Gradle中展示的两项目依赖的Okhttp版本](https://z3.ax1x.com/2021/10/13/5M6vnO.png)

或者：
在`framework`中，可以查看`MediaType.parse`的定义，发现其对应的Okhttp版本为：4.9.0，该API确实被标记为`@Deprecated`。
在`project`中，同样查看，发现对应的Okhttp版本为：3.14.9，在此版本中API并没有标记`@Deprecated`。
所以，应该是两个项目就目前的配置而言，是对应的Okhttp版本不一致，所以在一个项目中目标API可用，而另一个项目中却要求替换成新的写法。

## 解决方法

自然是将两个项目的Okhttp协调一致。
可供参考的方案：
显式的为`project`指定Okhttp依赖的版本。
```groovy

// project/build.gradle

dependencies {

    // ......

    api 'com.squareup.okhttp3:okhttp:4.9.0'

    // ......

}



```

**Comment by ExerciseBook** [comment]
十分感谢，我之前把这个问题在 okhttp 的项目里提了 issue ，维护者他们已经回复过我了。

确实是我操作有问题，我想当然地认为了项目依赖是会被传递的。应该是我还对 gradle 的版本管理不太熟悉。

**Comment by SalHe** [comment]
> 十分感谢，我之前把这个问题在 okhttp 的项目里提了 issue ，维护者他们已经回复过我了。
> 
> 确实是我操作有问题，我想当然地认为了项目依赖是会被传递的。应该是我还对 gradle 的版本管理不太熟悉。

没事，练练/xk。
如果真出现这种问题，感觉编译器或者IDE插件可能bug了。
